import React from "react";
import { useState } from "react";
// import axios from "axios";

import Head from "next/head";
import styles from '../styles/Home.module.css'

const Output = () => {

  const [attendees, setAttendees] = useState(null);
  const fetchURL = '';

  function fetchAttendees() {
    fetch(fetchURL)
    .then(resp => resp.json())
    .then(data => {
      console.log(data);
      setAttendees(data);
    });
  }
  
  return (
    <div className={styles.container}>
            <Head>
                <title>Google Sheets Data Output</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Data From Google Sheets
                </h1>
            <div>
            <h2>Attendee List</h2>
             <button onClick={fetchAttendees}>Get All Attendies Entries</button>
             
             <div className="attendees">
               {attendees && 
               attendees.map((attendee, i) => (
                 <ul key={i}>
                   <li>{attendee.name} - {attendee.email}</li>
                 </ul>
               ))}
             </div>
        </div>
            </main>
            <footer className={styles.footer}>
            </footer>
        </div>
  );
};

export default Output;